import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "~/components/browsing/topnav";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={`${GeistSans.variable}`}>
          <div className={"grid h-screen grid-rows-[auto,1fr]"}>
            <TopNav />
            <main className={"overflow-y-scroll"}>
              {children} {/*this is page*/}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
